#! /usr/bin/env bash

# The purpose of this custom AppRun script is
# to allow symlinking the AppImage and invoking
# the corresponding binary depending on which
# symlink was used to invoke the AppImage
# make sure errors in sourced scripts will cause this script to stop
set -e

HERE="$(readlink -f "$(dirname "$0")")"

BINARY_NAME=${BINARY_NAME:-"pyrogenesis"}

echo "To invoke the Actor editor:"
echo "BINARY_NAME=ActorEditor $0"
echo ""

if [ "$BINARY_NAME" = "pyrogenesis" ] || [ "$BINARY_NAME" = "0ad" ]; then
  exec "$HERE/usr/bin/pyrogenesis" "$@"
elif [ "$BINARY_NAME" = "ActorEditor" ]; then
  exec "$HERE/usr/bin/ActorEditor" "$@"
else
  exec "$HERE/usr/bin/pyrogenesis" "$@"
fi
