FROM ubuntu:focal
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update &&   \
    apt -y upgrade && \
    apt install -y  \
        build-essential \
        cargo   \
        cmake   \
        libboost-dev    \
        libboost-filesystem-dev \
        libboost-system-dev   \
        libcurl4-gnutls-dev \
        libenet-dev \
        libfmt-dev   \
        libfreetype6-dev    \
        libgloox-dev    \
        libicu-dev \
        libminiupnpc-dev \
        libogg-dev  \
        libopenal-dev   \
        libpng-dev  \
        libsdl2-dev \
        libsodium-dev   \
        libvorbis-dev \
        libvulkan-dev   \
        libwxgtk3.0-gtk3-dev \
        libxml2-dev \
        m4 \
        python3 \
        subversion \
        rustc   \
        zlib1g-dev &&  \
    apt install -y  \
        curl    \
        patchelf    \
        wget && \
    rm -rf /var/lib/apt/lists

ENV TOOLS_DIR="/tools"
RUN mkdir -p $TOOLS_DIR
ARG ARCH=x86_64
RUN /bin/bash -c 'cd $TOOLS_DIR \
    && curl -LO https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20220822-1/linuxdeploy-${ARCH}.AppImage \
    && chmod +x linuxdeploy-${ARCH}.AppImage \
    && ./linuxdeploy-${ARCH}.AppImage --appimage-extract \
    && rm ./linuxdeploy-${ARCH}.AppImage \
    && cd -'

# For some reason, if '/home/0adbuilder' exists,
# ./updateworkspaces.sh fails after the Collada
# build, when the python virtual environment is created.
# Using '-M' here so the home dir doesn't get created
RUN useradd -M 0adbuilder && passwd -d 0adbuilder

ENV DOCKER_0AD_BUILD=TRUE
# needed for spidermonkey build
ENV SHELL=/bin/bash

CMD ["/bin/bash","-l"]
