FROM debian:bullseye-slim
ENV ARCH=x86_64
ENV MINISIGN_VERSION="0.10"
ENV TOOLS_DIR="/tools"
ENV MINISIGN_PATH="$TOOLS_DIR/minisign-$MINISIGN_VERSION-linux/x86_64/minisign"

RUN apt update && apt install -y wget

RUN wget -nv https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
RUN chmod +x linuxdeploy-$ARCH.AppImage
RUN wget -nv https://github.com/jedisct1/minisign/releases/download/${MINISIGN_VERSION}/minisign-${MINISIGN_VERSION}-linux.tar.gz
RUN wget -nv https://github.com/jedisct1/minisign/releases/download/${MINISIGN_VERSION}/minisign-${MINISIGN_VERSION}-linux.tar.gz.minisig
RUN mkdir $TOOLS_DIR
RUN tar xf minisign-$MINISIGN_VERSION-linux.tar.gz -C $TOOLS_DIR
RUN $MINISIGN_PATH -Vm minisign-$MINISIGN_VERSION-linux.tar.gz -P RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3

WORKDIR $TOOLS_DIR
RUN ../linuxdeploy-$ARCH.AppImage --appimage-extract
RUN wget -nv https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh
RUN chmod +x linuxdeploy-plugin-gtk.sh

FROM andy5995/0ad-build-env:bionic
ENV TOOLS_DIR="/tools"
ENV BUILD_DIR="/build"
ENV MINISIGN_VERSION="0.10"
ENV MINISIGN_PATH="$TOOLS_DIR/minisign-$MINISIGN_VERSION-linux/x86_64/minisign"

COPY ./workflow.sh .
ENTRYPOINT ["/workflow.sh"]
COPY --from=0 $TOOLS_DIR $TOOLS_DIR
RUN chmod 777 $TOOLS_DIR
RUN mkdir -m 777 $BUILD_DIR
