name: Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - 'trunk'
    paths:
      - '.github/workflows/docker.yml'
      - 'Dockerfile*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ubuntu_codename: ['focal', 'jammy']
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-${{ matrix.ubuntu_codename }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/0ad-build-env:${{ matrix.ubuntu_codename }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/0ad-build-env:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/0ad-build-env:buildcache,mode=max
